import unittest
import pandas as pd
import shutil
import os
from river import synth
from calm_data_generator.generators.clinical.ClinicGeneratorBlock import (
    ClinicalDataGeneratorBlock,
)


class TestClinicalBlockGenerator(unittest.TestCase):
    def setUp(self):
        self.output_dir = "test_output_clinic_block"
        os.makedirs(self.output_dir, exist_ok=True)
        self.filename = "test_clinic_blocks.csv"

    def tearDown(self):
        if os.path.exists(self.output_dir):
            shutil.rmtree(self.output_dir)

    def test_initialization(self):
        gen = ClinicalDataGeneratorBlock()
        self.assertIsInstance(gen, ClinicalDataGeneratorBlock)

    def test_generate_clinical_blocks(self):
        gen = ClinicalDataGeneratorBlock()

        # We need a River generator instance as a "source" of randomness/concept
        # even though ClinicGenerator maps it to biological features
        river_gen = synth.Agrawal(seed=42)

        full_path = gen.generate(
            output_dir=self.output_dir,
            filename=self.filename,
            n_blocks=2,
            total_samples=20,
            n_samples_block=[10, 10],
            generators=[river_gen, river_gen],
            target_col="diagnosis",
            generate_report=False,
        )

        self.assertTrue(os.path.exists(full_path))
        df = pd.read_csv(full_path)

        # Check basic dimensions and block column
        self.assertEqual(len(df), 20)
        self.assertTrue("block" in df.columns)
        self.assertEqual(set(df["block"].unique()), {1, 2})

        # Check for clinical features presence (should be generated by ClinicGenerator)
        self.assertTrue("Age" in df.columns)
        self.assertTrue("Sex" in df.columns)


if __name__ == "__main__":
    unittest.main()
